In [3]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:
arr = np.array([[1,5,6],[3,5,6]])
print(arr)

[[1 5 6]
 [3 5 6]]


In [4]:
arr = np.array([[[3,4,2],[2,6,9]],[[1,0,3],[2,5,3]]])
print(arr[0,1,2])
arr.ndim

9


3

In [5]:
arr= np.array([[0,2],[4,5]], np.int8)
print(arr[1,1])
arr.ndim
print(arr.dtype)

5
int8


In [6]:
arr = np.array([1,4,5])
print(arr[2])
arr.ndim
print(arr.dtype)

5
int64


In [7]:
arr = np.array([
                [[3,4,2],[2,6,9]],
                [[1,0,3],[2,5,3]],
                [[22,32,21],[12,13,14]
                ]])
print(arr[2,1,2])
arr.ndim

14


3

In [8]:
arr= np.zeros((5,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
arr=np.ones((2,4))
print(arr)
print(arr.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(2, 4)


In [10]:
arr=np.arange(0,12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
arr=np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [12]:
arr=np.arange(10,0,-2)
print(arr)

[10  8  6  4  2]


In [13]:
arr=np.arange(0,1,0.3)
print(arr)

[0.  0.3 0.6 0.9]


In [14]:
# slicing
arr=np.array([11,12,13,14,14])
print(arr[1:4:2])

[12 14]


In [15]:
arr=np.array([[12,13,14],[1,2,3],[4,5,6]])
print(arr[0:2,1:3])
print(arr.flatten()) #flattening

[[13 14]
 [ 2  3]]
[12 13 14  1  2  3  4  5  6]


In [16]:
# reshaping
arr=np.array([1,2,3,4,5,6])
arr.shape
new_arr=arr.reshape(2,3)
print(new_arr)
new_arr.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [4]:
arr = np.array([2,3,4,5])
result = arr*2
add = (arr+3)
print(result)
print(add)

[ 4  6  8 10]
[5 6 7 8]


In [5]:
arr1=np.array([12,3,4])
arr2=np.array([11,23,3])
print(arr1+arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1**2)

[23 26  7]
[132  69  12]
[1.09090909 0.13043478 1.33333333]
[144   9  16]


In [6]:
salary=np.array([20000,30000,50000,60000])
print(salary*2.10)

[ 42000.  63000. 105000. 126000.]


In [7]:
# universal functions ufuncs

arr=np.array([4,9,16])
result=np.sqrt(arr)
print(result)
print(np.exp(arr))

[2. 3. 4.]
[5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [8]:
arr=np.array([9,3, 90, np.pi*30])
print(np.sin(arr))
print(np.cos(arr))

[ 4.12118485e-01  1.41120008e-01  8.93996664e-01 -1.07793678e-14]
[-0.91113026 -0.9899925  -0.44807362  1.        ]


In [9]:
# statistical operations
salary=np.array([2000,3000,1000,9000])
print(np.sum(salary))
print(np.mean(salary))
print(np.average(salary))
print(np.min(salary))
print(np.max(salary))
print(np.max(salary)-np.min(salary))
print(np.std(salary)) #SD
print(np.median(salary))
print(np.percentile(salary,20))
print(np.cumsum(salary))
print(np.cumprod(salary))
print(np.diff(salary))

15000
3750.0
3750.0
1000
9000
8000
3112.4748994971833
2500.0
1600.0
[ 2000  5000  6000 15000]
[          2000        6000000     6000000000 54000000000000]
[ 1000 -2000  8000]
