In [6]:
print("hello")

hello


## hello

- hii

In [8]:
import numpy as np

In [15]:
myarr = np.array([-128,127,4,5], np.int8)

In [19]:
print(myarr)
print(myarr.ndim)

[-128  127    4    5]
1


In [17]:
agesArr = np.array([[1,2,3]])

In [21]:
print(agesArr.ndim)
agesArr.shape

2


(1, 3)

In [33]:
heightsArr = np.array([[[1,2,3,4], [5,6,7,8], [7,8,9,10]]])

In [34]:
print(heightsArr)
heightsArr.ndim
heightsArr.shape

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 7  8  9 10]]]


(1, 3, 4)