In [2]:
import numpy as np

In [4]:
marks = np.array(
   [
    [20, 30, 40], # student1
    [10, 12,13],  # student2
    [25, 32, 46], # student3
   ]
)

In [6]:
print(np.sum(marks, axis=1)) # row wise
print(np.sum(marks, axis=0)) # col wise

[ 90  35 103]
[55 74 99]


In [7]:
print(np.mean(marks, axis=0))
print(np.mean(marks, axis=1))

[18.33333333 24.66666667 33.        ]
[30.         11.66666667 34.33333333]


In [8]:
print(np.max(marks, axis=0))

[25 32 46]


In [11]:
print(marks.mean(axis=0)) # avg marks of each student
print(marks.mean(axis=1)) # avg marks of each subject

[18.33333333 24.66666667 33.        ]
[30.         11.66666667 34.33333333]


In [13]:
# boolean indexing mean selecting element using condition
array = np.array([10, 20, 30, 40, 45, 50])
print(array>25)

[False False  True  True  True  True]


In [15]:
print(array[array>25])

[30 40 45 50]


In [17]:
print(array[(array>25) & (array<45)])

[30 40]


In [20]:
print(array[(array>25) | (array>45)])

[30 40 45 50]


In [21]:
array[array>20]=0
print(array)

[10 20  0  0  0  0]


In [26]:
marks = np.array([32, 45, 67, 78, 90, 23, 12])

In [27]:
print(marks[marks>25])

[32 45 67 78 90]


In [28]:
print(len(marks[marks>25]))

5


In [29]:
result = np.where(marks>=32, "Pass", "Fail")
print(result)

['Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Fail']


In [31]:
arr = np.array(
    [
        [20, 10, 20],
        [30, 40, 50]
    ])
row_sum = arr.sum(axis=1)
print(row_sum)
print(row_sum>60)
print(row_sum[row_sum>60])

[ 50 120]
[False  True]
[120]
